### ISSUE TITLE
Is it possible to rebuild corrupted mft and its mirror?

### ISSUE THREAD

**Issue by 5l1v3r1** [kacos2000/MFT_Browser#1]
Well, this is a commonly asked question and the answers on the internet are not sufficient. What if both mft and its mirror are both corrupted on the disk at some small particular points, can we recover the whole mft by some kind of reverse engineering? If so, how can we do it? I saw an article that a guy did it by changing some parameters with hex editor but the explanation was not so clear.

**Comment by kacos2000** [comment]
Depends on what is corrupted & how.
By reading the VBR, you get the start locations of the $MFT & $MFTMirr. 
From these locations, the first 1024bytes are the $MFT's own record, so you can get the $MFT size & datarun and carve it out or read it. 
If parts of records or the parts of the $MFT itself are zeroed out or unreadable, it would depend on how the tool you use handles that ..

**Comment by 5l1v3r1** [comment]
Is there a way that i can dump the error logs from the unreadable harddisk? So far i tried several tools like testdisk to recover mft but none of them succeeded. Only one tool called dm disk editor could read the harddisk because it recreates its own file system record temporarily. If so, i can share the result with you here for further investigation. Thank you for detailed answer.

**Comment by kacos2000** [comment]
try isobuster.com
