### ISSUE TITLE
cannot run MFTbrowser.ps1

### ISSUE THREAD

**Issue by noire-x** [kacos2000/MFT_Browser#5]
Hi there and thanks for this tool!
I cannot run the script, ive installed .NET Framework 4.8 and running powershell 5.1 natively since i am on windows 11. Set the execution Policy with the following command: Set-ExecutionPolicy RemoteSigned as well.
This is what i get, could you help me out?
Thanks a lot!
![image](https://github.com/kacos2000/MFT_Browser/assets/112881201/8661ecbb-8563-4f88-80bf-b7248e8a8641)

**Comment by kacos2000** [comment]
did you try the .exe from the releases?

**Comment by noire-x** [comment]
Hi there again and thanks for your reply!
Running the exe solved the issue!
Many thanks :)

**Comment by gitofamrit** [comment]
Getting this issue. Tried running as administrator. Still the issue persists.
I wanna make some changes in ps1 file.

**Comment by kacos2000** [comment]
Just re-checked it:

- Opened Win11 Sandbox
- downloaded the [.ps1](https://github.com/kacos2000/MFT_Browser/blob/master/MFTbrowser.ps1)
- opened terminal as Admin 
- navigated to the Downloads folder
- run "set-executionpolicy remotesigned"
- pressed 'A'
- run .\mftbrowser
- pressed 'A'

and it opened just fine. 
But feel free to change whatever you like ..
